export const LANDING_ROLES = [
  'Software Engineer',
  'Data Analyst',
  'Product Manager',
  'Data Engineer',
  'ML Engineer',
  'Business Analyst',
  'Data Scientist',
  'Cloud Engineer',
  'QA Engineer',
  'Product Analyst',
];

export const LANDING_PERSONAS = {
  grad: {
    badge: 'Before your OPT start date',
    badgeTone: 'teal',
    bar: 'Your OPT clock starts at graduation.',
    h1: 'Graduating soon and no job yet?',
    h1b: "Here's how international students land US tech offers before the OPT clock starts.",
    sub: 'A structured job-search system — resume, LinkedIn, targeted applications and mock interviews — planned around your graduation date.',
    cta: 'Get my free job-search plan',
    cta2: 'Start my plan before graduation',
    chips: [
      ['Week 1', 'Resume rebuilt for target roles'],
      ['Week 3', 'Applying to sponsors only'],
      ['Week 6', 'Final-round interview'],
    ],
    painTitle: 'Graduation is close. Your inbox is quiet.',
    pains: [
      'Hundreds of applications, almost no replies',
      "Recruiters see 'requires sponsorship' and move on",
      'No idea which companies actually sponsor',
      'Classmates are signing offers and you are not',
    ],
    clockLabel: 'Your OPT runway',
    timelineTitle: 'Start before the clock does.',
    caption:
      'On post-completion OPT you can be unemployed for up to 90 days in total. Most of the work should happen before day one.',
    milestones: [
      ['Now', 'Map target roles and employers that sponsor'],
      ['Weeks 1–2', 'Resume and LinkedIn rebuilt'],
      ['Weeks 3–6', 'Targeted applications and mock interviews'],
      ['Before OPT', 'Offers, negotiation and start date'],
    ],
    quote:
      'I started in my last semester with no interviews. We built the search around my OPT start date, and I signed an offer before graduation.',
    quoteBy: 'Product Analyst · F-1 → OPT',
    finalTitle: 'Every week before graduation is a week of head start.',
    stickyText: 'Free call · plan your search before OPT',
    lens: 'clock',
    lensLabel: 'Your OPT clock',
    lensRight: 'Starts at graduation',
    img: '/landing/grad.png',
    alt: 'International student working on a laptop in a university library at dusk',
  },
  switcher: {
    badge: 'For H-1B professionals',
    badgeTone: 'blue',
    bar: 'Every month you wait is another month underpaid.',
    h1: 'Stuck on H-1B with an employer who underpays you?',
    h1b: 'See how to move to a better role without restarting your visa clock.',
    sub: 'Positioning, resume and interview coaching for H-1B professionals planning a transfer to a better-fit employer.',
    cta: 'Plan my move',
    cta2: 'Map out my transfer',
    chips: [
      ['Step 1', 'Market pay benchmarked'],
      ['Step 2', 'Sponsor shortlist built'],
      ['Step 3', 'Offer signed, transfer filed'],
    ],
    painTitle: "You've outgrown the role. The visa makes it feel risky.",
    pains: [
      "You're paid below market and you know it",
      'Worried a move puts your status at risk',
      'No time to job-hunt around a full-time role',
      'Not sure which employers will file a transfer',
    ],
    clockLabel: 'Your move plan',
    timelineTitle: 'Your next role, mapped.',
    caption: 'You keep your current job the whole time. Nothing changes until you decide it should.',
    milestones: [
      ['Month 0', 'Benchmark your pay and target roles'],
      ['Month 1', 'Reposition resume and LinkedIn'],
      ['Months 1–3', 'Focused search with employers that sponsor'],
      ['Offer', 'Negotiate, then transfer'],
    ],
    quote:
      "I'd been underpaid for two years and assumed switching meant risking my status. We mapped the transfer out before I applied anywhere.",
    quoteBy: 'Senior Software Engineer · H-1B transfer',
    finalTitle: "The better-fit role won't wait for the perfect moment.",
    stickyText: 'Free call · map your H-1B move',
    img: '/landing/switcher.png',
    alt: 'Software engineer looking out of an office window at dusk',
  },
  layoff: {
    badge: 'Inside your 60-day grace period',
    badgeTone: 'warning',
    bar: 'Your 60-day grace period is already running.',
    h1: 'Laid off on H-1B? You have 60 days.',
    h1b: "Here's the fastest path to a new sponsoring employer.",
    sub: 'A coach helps you focus the time you have: repositioning your resume, targeting employers that sponsor, and getting interview-ready fast.',
    cta: 'Talk to a coach today',
    cta2: 'Get my plan on the call',
    chips: [
      ['First', 'Sponsor shortlist built'],
      ['Next', 'Resume rewritten'],
      ['Then', 'Mock interviews booked'],
    ],
    painTitle: 'The clock started the day you were let go.',
    pains: [
      '60 days feels like nothing — and it keeps shrinking',
      'Mass-applying and hearing nothing back',
      'Not sure which employers can file quickly',
      'Every day without a plan feels like a day lost',
    ],
    clockLabel: 'Your grace period',
    timelineTitle: 'Use the time you have on what matters.',
    caption:
      'The grace period lasts up to 60 days or until your I-94 ends, whichever comes first — so your coach plans the search around your date.',
    milestones: [
      ['First call', 'Your dates, target roles and sponsors'],
      ['Positioning', 'Resume and LinkedIn rewritten'],
      ['Search', 'Targeted applications and interview prep'],
      ['Offer', 'Negotiation and transfer'],
    ],
    quote:
      'I was laid off on a Tuesday. Within two weeks I had a rewritten resume, a clear list of sponsors and my first interviews lined up.',
    quoteBy: 'Data Engineer · H-1B, placed within grace period',
    finalTitle: 'Day one of your plan can be today.',
    stickyText: 'Free call · talk to a coach today',
    lens: 'clock',
    lensLabel: 'Grace period',
    lensRight: 'Up to 60 days',
    img: '/landing/layoff.png',
    alt: 'Tech professional planning at a kitchen table early in the morning',
  },
  explorer: {
    badge: 'No commitment',
    badgeTone: 'neutral',
    bar: 'The best time to plan a US move is before you make it.',
    h1: 'Thinking about a US tech career?',
    h1b: 'See the real path international candidates take — before you commit to anything.',
    sub: 'Understand the visa routes, realistic timelines and the skills US tech employers hire for. Learn first, decide later.',
    cta: 'Show me the real path',
    cta2: 'Talk it through with a coach',
    chips: [
      ['Route', 'Visa paths compared'],
      ['Roles', 'Target roles mapped'],
      ['Skills', 'Gaps identified'],
    ],
    painTitle: 'Everyone has an opinion. Few have the full picture.',
    pains: [
      'Conflicting advice about visas and timelines',
      "Not sure if a US master's is worth it",
      'No clear view of what US employers hire for',
      'Wary of spending money before understanding the path',
    ],
    clockLabel: 'The real path',
    timelineTitle: 'From abroad to a US tech role, step by step.',
    caption:
      'No commitment. The first call is about giving you the full picture, so you can decide with confidence.',
    milestones: [
      ['Explore', 'Compare routes: study, transfer, direct hire'],
      ['Prepare', 'Close skill and profile gaps'],
      ['Arrive', 'F-1 → OPT / STEM OPT job search'],
      ['Grow', 'H-1B and a long-term career'],
    ],
    quote:
      'I spent a few months just understanding the routes. When I committed to a master’s in the US, I already knew what employers wanted.',
    quoteBy: 'ML Engineer · pre-arrival → F-1 → STEM OPT',
    finalTitle: 'Get the full picture before you commit to anything.',
    stickyText: 'Free call · no commitment',
    img: '/landing/explorer.png',
    alt: 'Young professional at a café window with a laptop, looking out',
  },
  stemopt: {
    badge: 'On STEM OPT',
    badgeTone: 'teal',
    bar: 'Your STEM OPT extension has an end date.',
    h1: 'On STEM OPT and racing the H-1B lottery?',
    h1b: 'Get placed with employers who already sponsor — before your extension runs out.',
    sub: "A coach helps you target E-Verified employers with a sponsorship track record, so one lottery result doesn't decide your career.",
    cta: 'Plan my STEM OPT search',
    cta2: 'Map my runway on a call',
    chips: [
      ['First', 'E-Verified sponsors shortlisted'],
      ['Next', 'Resume rebuilt for target roles'],
      ['Then', 'Interviews with employers who file'],
    ],
    painTitle: 'Two clocks running at once.',
    painLine:
      'Your extension is counting down and the lottery is out of your hands. Where you apply is not.',
    pains: [
      'Your STEM OPT end date keeps getting closer',
      'Not selected in the lottery — or still waiting to find out',
      "STEM OPT needs an E-Verify employer, and many aren't",
      'Recruiters stall the moment sponsorship comes up',
    ],
    lens: 'clock',
    lensLabel: 'STEM OPT extension',
    lensRight: 'Lottery runs once a year',
    clockLabel: 'Your extension runway',
    timelineTitle: 'Spend the extension on employers who can keep you.',
    caption:
      'STEM OPT only works with E-Verify employers, and the H-1B lottery runs once a year. Your coach plans the search around both.',
    milestones: [
      ['First call', 'Your end date, lottery status and target roles'],
      ['Positioning', 'Resume and LinkedIn rebuilt for sponsors'],
      ['Search', 'Applications to E-Verified employers that sponsor'],
      ['Offer', 'Negotiation and sponsorship next steps'],
    ],
    quote:
      "I had one lottery attempt left on my extension. We stopped applying everywhere and focused on employers with a filing history — that's where my offer came from.",
    quoteBy: 'Data Scientist · STEM OPT → H-1B',
    finalTitle: 'Your extension is running. Your plan can start today.',
    stickyText: 'Free call · plan your STEM OPT search',
    img: '/landing/stemopt.png',
    alt: 'Software engineer at an office desk in the evening, looking at a calendar',
  },
  greencard: {
    badge: 'Green card holders',
    badgeTone: 'blue',
    bar: 'Fully work-authorized — and still screened like you need sponsorship?',
    h1: 'Green card holder, but still getting visa questions in every interview?',
    h1b: "Get matched with recruiters who already know you're work-authorized.",
    sub: "You don't need visa help. You need positioning that stops recruiters guessing — so the conversation is about the role, not your status.",
    cta: 'Upgrade my search',
    cta2: 'Fix my positioning',
    chips: [
      ['First', 'Status stated up front'],
      ['Next', 'Resume aimed at the next level'],
      ['Then', 'Recruiter calls about the job'],
    ],
    painTitle: "You're authorized. Your applications don't say so.",
    painLine:
      "Recruiters pattern-match on an international name or degree and assume sponsorship. That's a positioning problem — and it's fixable.",
    pains: [
      "Asked 'Will you need sponsorship?' in every screen",
      'Filtered out by ATS questions you answered correctly',
      "Passed over for roles you're overqualified for",
      'Stuck in lateral moves when you want an upgrade',
    ],
    lens: 'silence',
    sent: 120,
    replies: '0',
    repliesLabel: 'Calls about the actual role',
    clockLabel: 'Your upgrade path',
    timelineTitle: 'From screened out to shortlisted.',
    caption:
      'No visa strategy needed. Your coach focuses on positioning, target roles and the upgrade you actually want.',
    milestones: [
      ['First call', 'Target roles and your next level'],
      ['Positioning', 'Status clear in resume, LinkedIn and ATS answers'],
      ['Search', 'Recruiters and roles matched to your level'],
      ['Offer', 'Negotiate from a position of strength'],
    ],
    quote:
      "I'd had my green card for three years and still got sponsorship questions. Once my profile said it plainly, the calls were about the job.",
    quoteBy: 'Senior Product Manager · Green card',
    finalTitle: "Stop answering visa questions you don't need to answer.",
    stickyText: 'Free call · upgrade your search',
    img: '/landing/greencard.png',
    alt: 'Confident professional in a blazer waiting in a glass-walled meeting room',
  },
  citizen: {
    badge: 'US citizens · international background',
    badgeTone: 'blue',
    bar: 'Full eligibility. Still no callbacks.',
    h1: 'Zero visa friction, but still not landing interviews?',
    h1b: 'See how we position an international background so it reads as an asset.',
    sub: "An overseas degree or an unfamiliar name shouldn't cost you callbacks. A coach rebuilds how your background reads — so recruiters see range, not risk.",
    cta: 'Reposition my background',
    cta2: 'Show me how on a call',
    chips: [
      ['First', 'Overseas experience translated'],
      ['Next', 'Eligibility stated plainly'],
      ['Then', 'Callbacks from the right roles'],
    ],
    painTitle: 'Nobody will say it. The callback gap is real.',
    painLine:
      "An unfamiliar degree or name gets skimmed differently. You can't change the bias — you can change what recruiters see first.",
    pains: [
      'Fully eligible, still getting silence',
      'Overseas degree treated as a question mark',
      'International experience read as a gap, not a strength',
      'Watching less-qualified peers get the interviews',
    ],
    lens: 'silence',
    sent: 150,
    replies: '0',
    repliesLabel: 'Callbacks',
    clockLabel: 'Your repositioning',
    timelineTitle: 'Turn your background into the reason they call.',
    caption:
      'No visa talk. Your coach works on how your story reads — resume, LinkedIn and the first 30 seconds of every interview.',
    milestones: [
      ['First call', 'Where your applications stall today'],
      ['Positioning', 'International experience reframed as range'],
      ['Search', 'Roles where your background is an edge'],
      ['Offer', 'Interview story and negotiation'],
    ],
    quote:
      "I'm a citizen and still got asked about sponsorship. We rewrote my overseas experience as scope and impact, and the callbacks changed within weeks.",
    quoteBy: 'Software Engineer · US citizen',
    finalTitle: 'Your background is an asset. Make your resume say so.',
    stickyText: 'Free call · reposition your background',
    img: '/landing/citizen.png',
    alt: 'Confident tech professional with arms crossed at a co-working space',
  },
  h4: {
    badge: 'H4 EAD holders',
    badgeTone: 'teal',
    bar: "Restarting after a career gap? You're not starting from zero.",
    h1: 'On H4 EAD and restarting your career after a gap?',
    h1b: "Here's how to get hired by employers who understand EAD status.",
    sub: 'A coach helps you explain the gap with confidence, refresh your skills story and focus on employers comfortable hiring on an EAD.',
    cta: 'Restart my career',
    cta2: 'Plan my restart on a call',
    chips: [
      ['First', 'Career gap framed with confidence'],
      ['Next', 'Skills story refreshed'],
      ['Then', 'Employers who know EAD'],
    ],
    painTitle: 'The gap feels bigger on paper than it is.',
    painLine:
      "Employers hesitate when they don't understand an EAD tied to a spouse's status. Clear positioning answers that before they ask.",
    pains: [
      "A career gap you're not sure how to explain",
      "Employers unsure what 'H4 EAD' means for them",
      "Worry about your EAD depending on your spouse's status",
      'Applications going out, nothing coming back',
    ],
    lens: 'silence',
    sent: 80,
    replies: '0',
    repliesLabel: 'Interview calls',
    clockLabel: 'Your restart',
    timelineTitle: 'Back to work, one practical step at a time.',
    caption:
      'Your coach plans around your EAD validity and renewal dates, and helps you explain your status in one clear sentence.',
    milestones: [
      ['First call', 'Your gap, skills and EAD dates'],
      ['Positioning', 'Resume and LinkedIn that own the gap'],
      ['Search', 'Employers comfortable hiring on EAD'],
      ['Offer', 'Interview prep and start date'],
    ],
    quote:
      "I'd been out of work for four years and assumed nobody would take an EAD seriously. Learning to explain both in one line changed my interviews.",
    quoteBy: 'QA Engineer · H4 EAD',
    finalTitle: "Your restart doesn't have to wait for the perfect moment.",
    stickyText: 'Free call · plan your restart',
    img: '/landing/h4.png',
    alt: 'Woman at a home desk in the morning with a laptop and notebook',
  },
  l2: {
    badge: 'L2 EAD holders',
    badgeTone: 'teal',
    bar: "Your time here is tied to your spouse's assignment.",
    h1: 'On L2 EAD and rebuilding your US career?',
    h1b: "Get matched with employers who won't blink at your status.",
    sub: 'A coach helps you explain L2 work authorization clearly, target employers used to dependent status, and make the most of the time the assignment allows.',
    cta: 'Rebuild my US career',
    cta2: 'Plan around my timeline',
    chips: [
      ['First', 'L2 status explained in one line'],
      ['Next', 'Resume rebuilt for US roles'],
      ['Then', 'Employers who hire on EAD'],
    ],
    painTitle: 'Most recruiters have never hired someone on L2.',
    painLine:
      'Unfamiliar status slows every conversation, and your time in the US is tied to an assignment. You need a search that moves.',
    pains: [
      'Recruiters unsure whether L2 means you can work',
      'Your stay tied to the length of the assignment',
      "Overseas experience that doesn't translate on paper",
      'Starting over in a new country and a new market',
    ],
    lens: 'clock',
    lensLabel: 'Assignment timeline',
    lensRight: "Set by your spouse's role",
    clockLabel: 'Your assignment window',
    timelineTitle: 'Make the assignment count for your career too.',
    caption:
      'Your coach plans the search around the assignment dates, so you target roles that fit the time you have.',
    milestones: [
      ['First call', 'Assignment dates and target roles'],
      ['Positioning', 'Status and experience made clear'],
      ['Search', 'Employers familiar with dependent EAD'],
      ['Offer', 'Interview prep and negotiation'],
    ],
    quote:
      'Every recruiter asked what L2 meant. Once I could answer in one sentence, the conversations moved on to what I could actually do.',
    quoteBy: 'Business Analyst · L2 EAD',
    finalTitle: 'The assignment clock is running. Put it to work.',
    stickyText: 'Free call · plan around your timeline',
    img: '/landing/l2.png',
    alt: 'Woman working on a laptop in a newly moved-into apartment',
  },
  o1a: {
    badge: 'O-1A · by consultation',
    badgeTone: 'blue',
    bar: 'Senior and specialist roles, handled with care.',
    calm: true,
    h1: 'On O-1A or building your case for one?',
    h1b: 'Get placed with employers who already understand extraordinary-ability sponsorship.',
    sub: 'A consultative search for senior and niche roles — focused on employers and agents prepared to petition for, and maintain, O-1A status.',
    cta: 'Request a consultation',
    cta2: 'Discuss your case',
    chips: [
      ['Profile', 'Achievements and evidence mapped'],
      ['Match', 'Petitioner-ready employers'],
      ['Placement', 'The right senior role'],
    ],
    painTitle: 'Extraordinary ability, ordinary hiring process.',
    painLine:
      'O-1A needs a US employer or agent willing to petition. Senior and niche roles take longer to match — so this is a selective search, not a volume one.',
    pains: [
      'Finding an employer or agent willing to petition',
      'Senior and niche roles that take longer to match',
      'Hiring teams unfamiliar with O-1A',
      'Needing a role that also strengthens your case',
    ],
    lens: 'none',
    clockLabel: 'How we work',
    timelineTitle: 'A selective search for a senior career.',
    caption:
      'Fewer applications, better matched. Your coach works on positioning, target employers and the conversations that lead to a petition. For legal strategy, we work alongside your immigration attorney.',
    milestones: [
      ['Consultation', 'Your achievements, goals and status'],
      ['Positioning', 'A profile that reads as senior and singular'],
      ['Matching', 'Employers and agents ready to petition'],
      ['Offer', 'Negotiation and petition next steps'],
    ],
    quote:
      "I didn't need more applications. I needed the right few conversations with employers who understood O-1A — and that's what we worked on.",
    quoteBy: 'Principal ML Researcher · O-1A',
    finalTitle: 'Your career deserves a considered search.',
    stickyText: 'By consultation',
    img: '/landing/o1a.png',
    alt: 'Senior researcher standing in front of a glass whiteboard',
  },
  phd: {
    badge: 'PhD to industry',
    badgeTone: 'teal',
    bar: 'Your research is valuable. Your resume just needs translating.',
    h1: 'PhD ready to leave academia for industry?',
    h1b: 'See how we translate research experience into offers — visa status handled either way.',
    sub: 'Publications become impact. Methods become skills. A coach helps you turn your research record into an industry resume and interview story.',
    cta: 'Translate my research',
    cta2: 'Map my industry roles',
    chips: [
      ['Papers →', 'Impact statements'],
      ['Methods →', 'Industry skills'],
      ['Thesis →', 'Interview story'],
    ],
    painTitle: 'Five years of research. One page to explain it.',
    painLine:
      "Industry recruiters don't read CVs the way committees do. Your record needs translating into roles, impact and results.",
    pains: [
      'An academic CV industry recruiters skim past',
      'Not sure whether you fit research, data or product roles',
      "Publications that don't turn into interview answers",
      'Visa questions on top of the career switch',
    ],
    lens: 'silence',
    sent: 60,
    replies: '1',
    repliesLabel: 'Interview calls',
    clockLabel: 'The translation',
    timelineTitle: "Here's how your research becomes a resume.",
    caption:
      'F-1, OPT, STEM OPT, H-1B or anything else — your coach plans around your status, so you can focus on the switch.',
    milestones: [
      ['First call', 'Your research, skills and target roles'],
      ['Translation', 'Academic CV → industry resume'],
      ['Search', 'Roles where a PhD is an edge'],
      ['Offer', 'Technical interviews and negotiation'],
    ],
    quote:
      "My CV was twelve pages of publications. We turned it into one page of results, and I finally had answers when interviewers asked what I'd built.",
    quoteBy: 'Applied Scientist · PhD → industry',
    finalTitle: 'Your research already did the hard part.',
    stickyText: 'Free call · translate your research',
    img: '/landing/phd.png',
    alt: 'PhD researcher walking out of a university lab corridor with a laptop',
  },
};

export const DEFAULT_PAIN_LINE =
  'Mass applying is a waste of time. A system is what changes the outcome.';
